export const GET_COLLECTION_LIST = "GET_COLLECTION_LIST";
export const PRESENT_IMAGES = "PRESENT_IMAGES";
export const GET_USER_INFO = "GET_USER_INFO";
export const PRESENT_ONE_COLLECTION = "PRESENT_ONE_COLLECTION";
export const UPDATE_COLLECTION_LIST = "UPDATE_COLLECTION_LIST";
export const CLEAR_COLLECTION_HISTORY = "CLEAR_COLLECTION_HISTORY";
export const SHOW_COLLECTION_MODAL = "SHOW_COLLECTION_MODAL";
export const HIDE_COLLECTION_MODAL = "HIDE_COLLECTION_MODAL";
export const GET_IMAGE_INFO = "GET_IMAGE_INFO";
export const ADD_NEW_COLLECTION = "ADD_NEW_COLLECTION";
export const SHOW_IMG_MODAL = "SHOW_IMG_MODAL";
export const HIDE_IMG_MODAL = "HIDE_IMG_MODAL";

