export const GET_COLLECTION_LIST = "GET_COLLECTION_LIST";
export const PRESENT_IMAGES = "PRESENT_IMAGES";
export const GET_USER_INFO = "GET_USER_INFO";
export const PRESENT_ONE_COLLECTION = "PRESENT_ONE_COLLECTION";
export const UPDATE_COLLECTION_LIST = "UPDATE_COLLECTION_LIST";